# Generated by Django 5.1.7 on 2025-03-25 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('telephone', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tonnage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prix_unitaire', models.IntegerField(default=0)),
                ('quantite', models.IntegerField(default=1)),
                ('montant', models.IntegerField(default=0)),
                ('chiffonage', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_bl', models.CharField(blank=True, max_length=50, null=True)),
                ('statut', models.CharField(choices=[('enregistré', 'Enregistré')], default='enregistré', max_length=20)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.camion')),
            ],
        ),
        migrations.CreateModel(
            name='StatutCamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('attente', 'Attente'), ('panne', 'Panne'), ('off', 'Off')], default='attente', max_length=20)),
                ('camion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statut_camion', to='gestion.camion')),
            ],
        ),
    ]
