# Generated by Django 5.1.7 on 2025-03-25 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('enregistré', 'Enregistré')], default='enregistré', max_length=20),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='StatutCamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('En panne', 'En panne'), ('Travaille pas', 'Travaille pas')], default='attente', max_length=20)),
                ('camion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statut_camion', to='gestion.camion')),
            ],
        ),
    ]
