# Generated by Django 5.1.7 on 2025-03-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField()),
                ('fichier', models.FileField(upload_to='rapports/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
