# Generated by Django 5.1.7 on 2025-03-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_panne', 'En panne'), ('ne_travaille_pas', 'Ne travaille pas'), ('enregistre', 'Enregistré')], default='Enregistré', max_length=20),
        ),
    ]
