# Generated by Django 5.1.7 on 2025-03-20 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_livraison_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_panne', 'En panne'), ('ne_travaille_pas', 'Ne travaille pas'), ('enregistré', 'Enregistré')], default='Enregistré', max_length=20),
        ),
        migrations.CreateModel(
            name='StatutCamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_panne', 'En panne'), ('ne_travaille_pas', 'Ne travaille pas')], default='en_attente', max_length=20)),
                ('camion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.camion')),
            ],
        ),
    ]
