# Generated by Django 5.1.7 on 2025-06-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_rapport'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='verification',
            field=models.CharField(choices=[('verifié', 'Vérifié'), ('non_verifié', 'Non vérifié')], default='non_verifié', max_length=20),
        ),
    ]
