# Generated by Django 5.1.7 on 2025-03-21 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_livraison_statut_statutcamion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('enregistré', 'Enregistré')], default='enregistré', max_length=20),
        ),
        migrations.AlterField(
            model_name='statutcamion',
            name='camion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statut_camion', to='gestion.camion'),
        ),
        migrations.AlterField(
            model_name='statutcamion',
            name='statut',
            field=models.CharField(choices=[('attente', 'attente'), ('Panne', 'panne'), ('Off', 'Off')], default='attente', max_length=20),
        ),
    ]
