# Generated by Django 5.1.7 on 2025-03-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_statutcamion_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statutcamion',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_panne', 'En panne'), ('ne_travaille_pas', 'Ne travaille pas')], default='en_attente', max_length=20),
        ),
    ]
