# Generated by Django 5.1.7 on 2025-03-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_statutcamion_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statutcamion',
            name='statut',
            field=models.CharField(choices=[('attente', 'Attente'), ('en_panne', 'En panne'), ('ne_travaille_pas', 'Ne travaille pas')], default='attente', max_length=20),
        ),
    ]
