# Generated by Django 5.1.7 on 2025-03-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_statutcamion_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statutcamion',
            name='statut',
            field=models.CharField(choices=[('attente', 'Attente'), ('panne', 'Panne'), ('off', 'Off')], default='attente', max_length=20),
        ),
    ]
